---
title: "Data pipeline"
output: html_notebook
---

### Imports
```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(lubridate)
library(cbsodataR)
library(httr)
library(aweek)

```



### Get population data from CBS

```{r}
pop <- 
  cbs_get_data("83474NED") %>%
  filter(str_detect(Perioden, "\\d{4}MM\\d{2}")) %>%
  mutate(
    Date = date(parse_date_time(Perioden, "y m")),
    Population = BevolkingAanHetBeginVanDePeriode_1 
  ) %>%
  select("Date", "Population")

pop
```
### Age 

```{r}
cbs_get_data("03759ned", Geslacht = "T001038", BurgerlijkeStaat = "T001019") %>% head()
head(cbs_get_data("03759ned"))
```


### Get Maximum Temperature data from KNMI

```{r}
r <- POST(
  "http://projects.knmi.nl/klimatologie/daggegevens/getdata_dag.cgi",
  body = list(
    start = "19950101",
    end = strftime(today(), format = "%Y%m%d"),
    vars = "TX",
    stns = "ALL"
  )
)

temp <- content(r, as = "raw") %>%
  read_delim(
    ",",
    comment = "#",
    col_names = c("Station", "Date", "Temperature"),
    col_types = "ici",
    trim_ws = TRUE
  ) %>%
  drop_na() %>%
  mutate(Date = ymd(Date))
  # group_by(Date) %>%
  # summarise(
  #   Temperature = mean(Temperature)
  # )

head(temp)
```

### Get air quality data

Fill in missing days.

```{r}
air <- read_rds("../results/luchtmeetnet.Rds") %>%
  # group_by(Date, Variable) %>%
  # summarise(
  #   Value = mean(Value)
  # ) %>%
  # ungroup() %>%
  spread(Variable, Value) %>%
  select("Date", "PM2.5", "PM10", "NO2", "O3") %>%
  arrange(Date)

head(air)
```

Aggregate by week

```{r}
# air <- air.daily %>%
#   group_by(Date, Variable) %>%
#   drop_na() %>%
#   summarise(
#     Value = mean(Value)
#   ) %>%
#   ungroup() %>%
#   spread(Variable, Value) %>%
#   select("Year", "Week", "PM2.5", "PM10", "NO2") %>%
#   arrange(desc(Year), desc(Week))
# 
# air
```


```{r}
data.joined <- mort %>%
  union_all(pop) %>%
  union_all(temp) %>%
  union_all(air) %>%
  mutate(
    YearWeek = ISOweek::ISOweek(Date)
  ) %>%
  group_by(YearWeek) %>%
  summarise(
    Days = (max(Date) - min(Date) + 1) %>% as.numeric(units = "days"),
    StartPeriod = min(Date),
    Date = max(Date),
    Deaths = sum(Deaths, na.rm = T),
    Population = last(na.omit(Population), default = NA),
    Temperature = mean(Temperature, na.rm = T),
    PM2.5 = mean(PM2.5, na.rm = T),
    PM10 = mean(PM10, na.rm = T),
    NO2 = mean(NO2, na.rm = T),
    O3 = mean(O3, na.rm = T)
  ) %>%
  filter(Date <= max(mort$Date)) %>%
  arrange(desc(Date)) %>%
  fill(Population, .direction = "downup") 

data.joined
```

### Calculate the mortality rate

We will calculate the mortality rate the deaths by 1,000,000 inhabitants.
Additionally, we'll add columns for mortality rates in the previous 8 weeks.


```{r}

data <- data.joined %>%
  mutate(MortalityRate = Deaths * 100000 / Population / Days * 7, # to normalise week 53 and 1 
         Regio = "NL",
         Interval = "week",
         Period = str_match(YearWeek, "W(\\d+)") %>% .[,2] %>% as.numeric(),
         Year = str_match(YearWeek, "(\\d{4})") %>% .[,2] %>% as.numeric(),
         "MortalityRate.-1" = lag(MortalityRate, 1, order_by = Date),
         "MortalityRate.-2" = lag(MortalityRate, 2, order_by = Date),
         "MortalityRate.-3" = lag(MortalityRate, 3, order_by = Date),
         "MortalityRate.-4" = lag(MortalityRate, 4, order_by = Date),
         "MortalityRate.-5" = lag(MortalityRate, 5, order_by = Date),
         "MortalityRate.-6" = lag(MortalityRate, 6, order_by = Date),
         "MortalityRate.-7" = lag(MortalityRate, 7, order_by = Date),
         "MortalityRate.-8" = lag(MortalityRate, 8, order_by = Date),
         "MortalityRate.-9" = lag(MortalityRate, 5, order_by = Date),
         "MortalityRate.-10" = lag(MortalityRate, 6, order_by = Date),
         "MortalityRate.-11" = lag(MortalityRate, 7, order_by = Date),
         "MortalityRate.-12" = lag(MortalityRate, 8, order_by = Date),
        ) %>%
  select(-Days, -StartPeriod, -YearWeek)
data
```

### Save data

```{r}
write_rds(data, "../results/data.Rds")
```

```{r}
data %>% group_by(year(Date)) %>% summarise(M = mean(MortalityRate)) %>% arrange(desc(M))
```

